docs: add permissions section (#90)
**Context**

have setup this Github action on ipedis organisation for both 
 - public repository 
 - private repository
  
On the public repository i was able to setup with the example present on
the readme. For the private repository run was refuse due to a lack of
permission.

```
Run dequelabs/axe-linter-action@v1
Error: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#list-pull-requests-files
```

when i dig on the project i saw on
[git.ts](https://github.com/dequelabs/axe-linter-action/blob/main/src/git.ts)
the action require to :
 - read commits
 - read pull requests

No QA Required